$axure.loadCurrentPage({
  "url":"schedule_day_2.html",
  "generationDate":new Date(1413916421292.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69db174b7f724d2fa089581319cfb248",
    "type":"Axure:Page",
    "name":"Schedule_day_2",
    "notes":{
      "Instructions":"<p><span>Schedule Screen</span></p><p><span>&nbsp; - Specific schedule a short description is displayed</span></p><p><span>&nbsp; - User can change time, title, and description</span></p><p><span>&nbsp; - User will set which personal preferences should be displayed at this schedule</span></p><p><span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; - So when the schedule is uploaded on the car and the user clicks the profile icon</span></p><p><span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; on the gps screen only work and family locations are displayed between 7:30-8:30</span></p><p><span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; - Radio will be used this time with the specific station set by the user through the personal settings screen</span></p><p><span>&nbsp;&nbsp; - Clicking month opens the month screen</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7de4aac665434e2bb9454f928e4889b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df49a48343c74072bb19e3f546fe89e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/schedule_day_2/u0.png"}},
{
          "id":"9529e27e644e43449c7cb25553e31a00",
          "label":"Month",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":66},
            "size":{
              "width":106,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Schedule_month in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"schedule_month.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"203b1f20845a493da641f10bc32511a6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"8caddc4434814f9799cae10867a678a8",
          "label":"Back",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":40,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Schedule in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Schedule in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6a294f7eb86a4632a5d992d3a19306e1",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "7de4aac665434e2bb9454f928e4889b2":{
      "scriptId":"u0"},
    "df49a48343c74072bb19e3f546fe89e2":{
      "scriptId":"u1"},
    "9529e27e644e43449c7cb25553e31a00":{
      "scriptId":"u2"},
    "8caddc4434814f9799cae10867a678a8":{
      "scriptId":"u3"}}});