$axure.loadCurrentPage({
  "url":"mobile_main.html",
  "generationDate":new Date(1413920305974.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"X",
"Y",
"GPSx",
"GPSy",
"Prox",
"Proy",
"Musicx",
"Musicy",
"Newappx",
"Newappy",
"Settingsx",
"Settingsy",
"swapx",
"swapy",
"Customize"],
  "page":{
    "packageId":"3ac908ce7c5348aba8fbffccccdbd890",
    "type":"Axure:Page",
    "name":"Mobile Main",
    "notes":{
      "Instructions":"<p><span>Volvo Profile Home Screen </span></p><p><span>&nbsp; - Click Profile to open the personal settings screen</span></p><p><span>&nbsp; - Click Schedule to open the personal schedule screen</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"445f015174c74b309780998cf882d72d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c581e310e7794e83ae477d4361d7deac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_main/u0.jpg"}},
{
          "id":"36fa7536fd944895b9bd40886bd78bb5",
          "label":"Profile",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":510.000030517578},
            "size":{
              "width":87,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0f3469195b81438ca4999269c145efb1",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ef6637a606aa44afa69d3820a7ac0eb0",
          "label":"Schedule",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":570},
            "size":{
              "width":121,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"Open Schedule in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"schedule.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"82901b700d2f4a4cae33da1442b42254",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "445f015174c74b309780998cf882d72d":{
      "scriptId":"u0"},
    "c581e310e7794e83ae477d4361d7deac":{
      "scriptId":"u1"},
    "36fa7536fd944895b9bd40886bd78bb5":{
      "scriptId":"u2"},
    "ef6637a606aa44afa69d3820a7ac0eb0":{
      "scriptId":"u3"}}});