$axure.loadCurrentPage({
  "url":"gps.html",
  "generationDate":new Date(1413920306491.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"X",
"Y",
"GPSx",
"GPSy",
"Prox",
"Proy",
"Musicx",
"Musicy",
"Newappx",
"Newappy",
"Settingsx",
"Settingsy",
"swapx",
"swapy",
"Customize"],
  "page":{
    "packageId":"cc0d54215fd14d1498425779ccad9abd",
    "type":"Axure:Page",
    "name":"GPS",
    "notes":{
      "Instructions":"<p><span>GPS Screen Interactions:</span></p><p><span>&nbsp;</span></p><p><span>Menu</span></p><p><span>- You can swipe up the menu on the bottom to get access to more options</span></p><p><span>- By clicking the outer left icon (restaurants), relevant locations will appear, the popup window (Lilla Paris)</span></p><p><span>&nbsp; notices the closest open restaurant in the map.</span></p><p><span>- Similarly you can toggle/on off the rest of the icons to display fuel stations, parking spots and personal locations (from left to right)</span></p><p><span>- The outer right icon (profile icon) displays only the preferable locations that the user has saved through the mobile app</span></p><p><span>&nbsp;</span></p><p><span>Search</span></p><p><span>- Clicking on the map, the search function appears</span></p><p><span>- Typing &quot;le pain&quot; in this interactive screen, two relevant items appear.</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7e856b1fcee40eca3c0326b9a11acd6",
          "label":"Map",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":982,
              "height":786}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1db23142e7364deba47ce76e02160cc8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1189bde4edd8457783cb158bf908b08c",
                  "label":"",
                  "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":982,
                      "height":786},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3cab007fb05047e69caca6f0b5eea321",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":982,
                          "height":786},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Map to State2 fade out 500ms fade in 300ms show if hidden",
                              "panelsToStates":[{
                                  "panelPath":["a7e856b1fcee40eca3c0326b9a11acd6"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":300},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/gps/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"21b487f43c7b43f98e2e60500fc739e7",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5b85898c1d704170b866c61ff24f6e1d",
                  "label":"",
                  "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":982,
                      "height":786},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87f199dba5ce4527aeac84461b4fd9c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":982,
                          "height":786},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u3.jpg"}},
{
                  "id":"23b9dad7fa95400fb8676ad7fcfdc5fe",
                  "label":"Search",
                  "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":94,
                      "y":56},
                    "size":{
                      "width":767,
                      "height":51}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"5b5bd91506cb4baa9f73269e33db275f",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"4b77814d3e7b4b85ac67643628282790",
                          "label":"Search Unclicked",
                          "parentDynamicPanel":"23b9dad7fa95400fb8676ad7fcfdc5fe",
                          "panelIndex":0,
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontName":"'Volvo Sans Pro Light', 'Volvo Sans Pro'",
                            "fontSize":"24px",
                            "fontWeight":"300",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFA4A4A4,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":767,
                              "height":51}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Search to State2 show if hidden",
                                      "panelsToStates":[{
                                          "panelPath":["23b9dad7fa95400fb8676ad7fcfdc5fe"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":true,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"8f864a0e1c8b488d904ccdf97e96a6b9",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"bfa8f8e8b5f3431a862317c9bc3d09b2",
                          "label":"Search writing",
                          "parentDynamicPanel":"23b9dad7fa95400fb8676ad7fcfdc5fe",
                          "panelIndex":1,
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontName":"'Volvo Sans Pro Light Light', 'Volvo Sans Pro Light'",
                            "fontSize":"24px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFA4A4A4,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":767,
                              "height":51}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onKeyUp":{
                              "description":"OnKeyUp",
                              "cases":[{
                                  "description":"Case 1<br> (If text on Search writing contains &quot;Le p&quot; or text on Search writing contains &quot;Le pa&quot; or text on Search writing contains &quot;Le pai&quot; or text on Search writing contains &quot;Le pain&quot;)",
                                  "isNewIfGroup":false,
                                  "condition":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"ValueContains",
                                      "arguments":[{
                                          "exprType":"fcall",
                                          "functionName":"GetWidgetText",
                                          "arguments":[{
                                              "exprType":"pathLiteral",
                                              "isThis":false,
                                              "isFocused":false,
                                              "isTarget":false,
                                              "value":["bfa8f8e8b5f3431a862317c9bc3d09b2"]}]},
{
                                          "exprType":"stringLiteral",
                                          "value":"Le p",
                                          "stos":[]}]},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"||",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"ValueContains",
                                        "arguments":[{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["bfa8f8e8b5f3431a862317c9bc3d09b2"]}]},
{
                                            "exprType":"stringLiteral",
                                            "value":"Le pa",
                                            "stos":[]}]},
                                      "rightExpr":{
                                        "exprType":"binaryOp",
                                        "op":"||",
                                        "leftExpr":{
                                          "exprType":"fcall",
                                          "functionName":"ValueContains",
                                          "arguments":[{
                                              "exprType":"fcall",
                                              "functionName":"GetWidgetText",
                                              "arguments":[{
                                                  "exprType":"pathLiteral",
                                                  "isThis":false,
                                                  "isFocused":false,
                                                  "isTarget":false,
                                                  "value":["bfa8f8e8b5f3431a862317c9bc3d09b2"]}]},
{
                                              "exprType":"stringLiteral",
                                              "value":"Le pai",
                                              "stos":[]}]},
                                        "rightExpr":{
                                          "exprType":"fcall",
                                          "functionName":"ValueContains",
                                          "arguments":[{
                                              "exprType":"fcall",
                                              "functionName":"GetWidgetText",
                                              "arguments":[{
                                                  "exprType":"pathLiteral",
                                                  "isThis":false,
                                                  "isFocused":false,
                                                  "isTarget":false,
                                                  "value":["bfa8f8e8b5f3431a862317c9bc3d09b2"]}]},
{
                                              "exprType":"stringLiteral",
                                              "value":"Le pain",
                                              "stos":[]}]}}}},
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Show Le Pain French fade 500 ms,<br>Le pain Italian fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["b6dfc909bdc14431ad4d234ab055ed68"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}},
{
                                          "objectPath":["42adec42b34945889fa3ffaddecfbf23"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]},
{
                                  "description":"Case 2<br> (Else If True)",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide Le Pain French fade 200 ms,<br>Le pain Italian fade 100 ms",
                                      "objectsToFades":[{
                                          "objectPath":["b6dfc909bdc14431ad4d234ab055ed68"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "easing":"fade",
                                              "duration":200,
                                              "showType":"none"}}},
{
                                          "objectPath":["42adec42b34945889fa3ffaddecfbf23"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "easing":"fade",
                                              "duration":100,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"b6dfc909bdc14431ad4d234ab055ed68",
                  "label":"Le Pain French",
                  "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":61,
                      "y":108},
                    "size":{
                      "width":827,
                      "height":52},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"7de0c764a36046f4b37991e7ef8b1859",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"dc982a81bac944499cfe6ec69ec2dee2",
                          "label":"",
                          "parentDynamicPanel":"b6dfc909bdc14431ad4d234ab055ed68",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":827,
                              "height":52},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bf3256edd094403195c3094dd8c36ce5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b6dfc909bdc14431ad4d234ab055ed68",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":827,
                                  "height":52},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/gps/u9.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"42adec42b34945889fa3ffaddecfbf23",
                  "label":"Le pain Italian",
                  "parentDynamicPanel":"a7e856b1fcee40eca3c0326b9a11acd6",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":61,
                      "y":160},
                    "size":{
                      "width":827,
                      "height":48},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"b10081e0f782419e927d59a9a86415ce",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ec4907af9e04429babb079e298278916",
                          "label":"",
                          "parentDynamicPanel":"42adec42b34945889fa3ffaddecfbf23",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":827,
                              "height":48},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d19e245feaa24d7499acfbf10ea38650",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"42adec42b34945889fa3ffaddecfbf23",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":827,
                                  "height":48},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/gps/u12.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"06ed96fd273c42368d2b89e69dc94f77",
          "label":"Border",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":558},
            "size":{
              "width":200,
              "height":18}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2b84d38211e14d64ba34b8b35a664691",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e4a42adef0dc4314bad2a1f557a7623b",
          "label":"Border",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":568},
            "size":{
              "width":200,
              "height":18}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"02f48204435b4d97be8fe1de87f24421",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"17e4645246cd43dd9432d74867275b14",
          "label":"LillaParisPoint",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":546,
              "y":416},
            "size":{
              "width":32,
              "height":41},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c5cd550423e84824a9496523190cbc65",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9584f1f17a3242c5ad81386d4813ed14",
                  "label":"",
                  "parentDynamicPanel":"17e4645246cd43dd9432d74867275b14",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":29,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aae82c4c9f0c4231abaf0895931c7e37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"17e4645246cd43dd9432d74867275b14",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":29,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2861c88ced0c40f196eef7ec87ef76ad",
          "label":"Lepainfrancais",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":359,
              "y":571},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"4bf40596a3554ba5b012b79a1c2e4b52",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"af499a8e1e7745609f0cf7bffa00eb66",
                  "label":"",
                  "parentDynamicPanel":"2861c88ced0c40f196eef7ec87ef76ad",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":29,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d9dd85f54664f6bb01808bcf6f8cb1e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2861c88ced0c40f196eef7ec87ef76ad",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":29,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"344c763ece0a4224bcfc35a36a14f424",
          "label":"DaMatteo",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":104,
              "y":482},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"02428c8cce3f41308b6e827a13de9e13",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a0fbc40adfc443ad904cf1d92a3095d4",
                  "label":"",
                  "parentDynamicPanel":"344c763ece0a4224bcfc35a36a14f424",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":29,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0061b0fbe4b24039886b569023b14e89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"344c763ece0a4224bcfc35a36a14f424",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":29,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f038a670bc534526a2d1277ae31af188",
          "label":"Fuel Stations",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":572,
              "y":220},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e36e5ecc75e44cf092601a7f7d0d6b47",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"85b5f5a26cfe4cc899c3ffa8df785070",
                  "label":"",
                  "parentDynamicPanel":"f038a670bc534526a2d1277ae31af188",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b137f8a25e749ed8bacdfebf1fa8507",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f038a670bc534526a2d1277ae31af188",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u26.png"}},
{
                  "id":"bdb8d5aff2464eb3931f8c95ec82ba7c",
                  "label":"",
                  "parentDynamicPanel":"f038a670bc534526a2d1277ae31af188",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":228,
                      "y":250},
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f823a7286a847e1ac586db1cf2ba9b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f038a670bc534526a2d1277ae31af188",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":228,
                          "y":250},
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u26.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9ee9e81928e24a4197787fafabfca78e",
          "label":"Profile_pos",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":62,
              "y":229},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"6a822af9fca844faa3e920000f473188",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"56df43801f014a8c9d742616da99916b",
                  "label":"",
                  "parentDynamicPanel":"9ee9e81928e24a4197787fafabfca78e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42f70840504b4587beb4f2b70444ecc6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9ee9e81928e24a4197787fafabfca78e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u31.png"}},
{
                  "id":"83faa0e8e6e042e2bd090f0510a97d93",
                  "label":"",
                  "parentDynamicPanel":"9ee9e81928e24a4197787fafabfca78e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":456,
                      "y":192},
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3beadc99a1947a0bd056241a2c070e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9ee9e81928e24a4197787fafabfca78e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":456,
                          "y":192},
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u31.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c5d6a857eb4c45ff8a563fb357952f37",
          "label":"Parking_pos",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":151,
              "y":482},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5f92caa576ad4eeda1a2946084e1451d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fd05f527bff94d8db756f463cbe6b812",
                  "label":"",
                  "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":326,
                      "y":36},
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3743e2a21074ec5916a7be903f3ffdd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":326,
                          "y":36},
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u36.png"}},
{
                  "id":"8f918dbfe46c40eb99a33d32ce9fa9af",
                  "label":"",
                  "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff07ca78d75b49b582f1af1ebd6d47a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":65},
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u36.png"}},
{
                  "id":"4bf2b7e04812431ba12468300b114725",
                  "label":"",
                  "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":509,
                      "y":0},
                    "size":{
                      "width":29,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"867bc32adfa7431d8d7e6e1ff5e0beef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c5d6a857eb4c45ff8a563fb357952f37",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":509,
                          "y":0},
                        "size":{
                          "width":29,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u36.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"03c85fc399c648e9946d50960ad49cfd",
          "label":"Menu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":718},
            "size":{
              "width":982,
              "height":228}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeUp":{
              "description":"OnSwipeUp",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move This to (0,548) linear 700ms",
                      "objectsToMoves":[{
                          "objectPath":["03c85fc399c648e9946d50960ad49cfd"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"548",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":700}}}]}]}]},
            "onSwipeDown":{
              "description":"OnSwipeDown",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move This to (0,718) linear 700ms",
                      "objectsToMoves":[{
                          "objectPath":["03c85fc399c648e9946d50960ad49cfd"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"718",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":700}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8fe4d5f55fdd46bf92568dda1f741393",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"41f5332d7d7e40aea1169a71e413e315",
                  "label":"",
                  "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":1},
                    "size":{
                      "width":982,
                      "height":228},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"247999c2cfd043a9a81a15821385ba5b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":1},
                        "size":{
                          "width":982,
                          "height":228},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u43.png"}},
{
                  "id":"7ff8bd5bbc2946c0b0bc926d7a1c1e40",
                  "label":"Restaurants",
                  "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":133,
                      "y":63},
                    "size":{
                      "width":145,
                      "height":145}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"9d7c1b779d574632a18e775d609bd1cb",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"1aadfffa46874d4291091f2406706e26",
                          "label":"",
                          "parentDynamicPanel":"7ff8bd5bbc2946c0b0bc926d7a1c1e40",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0184fb4a02ab46a7a448e529b838e803",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7ff8bd5bbc2946c0b0bc926d7a1c1e40",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Restaurants to Next show if hidden wrap",
                                      "panelsToStates":[{
                                          "panelPath":["7ff8bd5bbc2946c0b0bc926d7a1c1e40"],
                                          "stateInfo":{
                                            "setStateType":"next",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":true,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Show LillaParisPoint fade 500 ms,<br>LillaParis fade 1000 ms,<br>Lepainfrancais fade 500 ms,<br>DaMatteo fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["17e4645246cd43dd9432d74867275b14"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}},
{
                                          "objectPath":["c9a55350cb5140bd9d39cf8d2888d092"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":1000,
                                              "showType":"none"}}},
{
                                          "objectPath":["2861c88ced0c40f196eef7ec87ef76ad"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}},
{
                                          "objectPath":["344c763ece0a4224bcfc35a36a14f424"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u46.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"fb915530e6d44be1be6a3de6f9191cb2",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"509dc05f893647c9b510846f3531a7fd",
                          "label":"",
                          "parentDynamicPanel":"7ff8bd5bbc2946c0b0bc926d7a1c1e40",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"354575cf587c4e4382f3608fe0c582ed",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7ff8bd5bbc2946c0b0bc926d7a1c1e40",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Restaurants to State1 show if hidden,<br>Menu to Next show if hidden wrap",
                                      "panelsToStates":[{
                                          "panelPath":["7ff8bd5bbc2946c0b0bc926d7a1c1e40"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":true,
                                            "options":{
                                              "compress":false}}},
{
                                          "panelPath":["03c85fc399c648e9946d50960ad49cfd"],
                                          "stateInfo":{
                                            "setStateType":"next",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":true,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Hide LillaParisPoint,<br>LillaParis,<br>DaMatteo",
                                      "objectsToFades":[{
                                          "objectPath":["17e4645246cd43dd9432d74867275b14"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["c9a55350cb5140bd9d39cf8d2888d092"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["344c763ece0a4224bcfc35a36a14f424"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u48.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"3083a0880e8e4ff2a306f8a8e61ad379",
                  "label":"Fuel",
                  "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":315,
                      "y":63},
                    "size":{
                      "width":145,
                      "height":145}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"0b0cd790b1c2451187c1dbd58112cda3",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"e9ae733247c84c629ec32d411da72f49",
                          "label":"",
                          "parentDynamicPanel":"3083a0880e8e4ff2a306f8a8e61ad379",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"11fc0f5fe2b749169270c83488be243f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"3083a0880e8e4ff2a306f8a8e61ad379",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Fuel to State2",
                                      "panelsToStates":[{
                                          "panelPath":["3083a0880e8e4ff2a306f8a8e61ad379"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Show Fuel Stations fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["f038a670bc534526a2d1277ae31af188"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u51.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"09bd1e164f0d4a0e86358591d0511f6e",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"8d4e58f2b7204e14adde2f9f9d004fb9",
                          "label":"",
                          "parentDynamicPanel":"3083a0880e8e4ff2a306f8a8e61ad379",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"687a121037474323bb48bc8cf726364b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"3083a0880e8e4ff2a306f8a8e61ad379",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Fuel to State1",
                                      "panelsToStates":[{
                                          "panelPath":["3083a0880e8e4ff2a306f8a8e61ad379"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Hide Fuel Stations fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["f038a670bc534526a2d1277ae31af188"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u53.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ce2bac0a939843a79795e2565e969744",
                  "label":"Parking",
                  "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":491,
                      "y":63},
                    "size":{
                      "width":145,
                      "height":145}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"84f61a09fded43d88bd509a688c97071",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"aa5011c92b3a41a9a13445cfda0f5804",
                          "label":"",
                          "parentDynamicPanel":"ce2bac0a939843a79795e2565e969744",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ee5de38c0fac4ff2b99a79772c44453c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"ce2bac0a939843a79795e2565e969744",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Parking to State2",
                                      "panelsToStates":[{
                                          "panelPath":["ce2bac0a939843a79795e2565e969744"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Show Parking_pos fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["c5d6a857eb4c45ff8a563fb357952f37"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u56.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"b37f7653437441a396fb9c85157ec2eb",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"5ec25adda8e24c47af47196607bdd8aa",
                          "label":"",
                          "parentDynamicPanel":"ce2bac0a939843a79795e2565e969744",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fadd9412665b4562a4ca2e5e3f52147e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"ce2bac0a939843a79795e2565e969744",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Parking to State1",
                                      "panelsToStates":[{
                                          "panelPath":["ce2bac0a939843a79795e2565e969744"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Hide Parking_pos fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["c5d6a857eb4c45ff8a563fb357952f37"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u58.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"b6980d0021ce4fc687723a4a93b98bdb",
                  "label":"Profile",
                  "parentDynamicPanel":"03c85fc399c648e9946d50960ad49cfd",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":678,
                      "y":63},
                    "size":{
                      "width":145,
                      "height":145}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"fe6aa9e8d487419b8bfc98550b4c3a89",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ab2274655d9d47db82f035348798e766",
                          "label":"",
                          "parentDynamicPanel":"b6980d0021ce4fc687723a4a93b98bdb",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9eac0487c2f446b88ba927ee36e9cd88",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b6980d0021ce4fc687723a4a93b98bdb",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Profile to State2",
                                      "panelsToStates":[{
                                          "panelPath":["b6980d0021ce4fc687723a4a93b98bdb"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":true,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Show Profile_pos fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["9ee9e81928e24a4197787fafabfca78e"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u61.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"0c718bf6080240768c4982ab414a3536",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ed90a1242d1b45648ae496bf05503cc2",
                          "label":"",
                          "parentDynamicPanel":"b6980d0021ce4fc687723a4a93b98bdb",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":145,
                              "height":145},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2b64c6f79b4e45758bc9caf4df255b2c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b6980d0021ce4fc687723a4a93b98bdb",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":145,
                                  "height":145},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Profile to State1",
                                      "panelsToStates":[{
                                          "panelPath":["b6980d0021ce4fc687723a4a93b98bdb"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"Hide Profile_pos fade 500 ms",
                                      "objectsToFades":[{
                                          "objectPath":["9ee9e81928e24a4197787fafabfca78e"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "easing":"fade",
                                              "duration":500,
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/gps/u63.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c0d49ac680cd474ebf3304d0c7da5aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":777},
            "size":{
              "width":982,
              "height":342},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd1decd3b7f4dbda141704e8810d7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":777},
                "size":{
                  "width":982,
                  "height":342},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gps/u65.png"}},
{
          "id":"c9a55350cb5140bd9d39cf8d2888d092",
          "label":"LillaParis",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":183,
              "y":218},
            "size":{
              "width":368,
              "height":209},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3869a1729cf34055a6f3c99d9cb5eda7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8bd156236da744e19a637efaef624066",
                  "label":"",
                  "parentDynamicPanel":"c9a55350cb5140bd9d39cf8d2888d092",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":368,
                      "height":209},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b9e20ab20da4680b064a69d9a22351d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c9a55350cb5140bd9d39cf8d2888d092",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":368,
                          "height":209},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/gps/u68.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a7e856b1fcee40eca3c0326b9a11acd6":{
      "scriptId":"u0"},
    "1189bde4edd8457783cb158bf908b08c":{
      "scriptId":"u1"},
    "3cab007fb05047e69caca6f0b5eea321":{
      "scriptId":"u2"},
    "5b85898c1d704170b866c61ff24f6e1d":{
      "scriptId":"u3"},
    "87f199dba5ce4527aeac84461b4fd9c2":{
      "scriptId":"u4"},
    "23b9dad7fa95400fb8676ad7fcfdc5fe":{
      "scriptId":"u5"},
    "4b77814d3e7b4b85ac67643628282790":{
      "scriptId":"u6"},
    "bfa8f8e8b5f3431a862317c9bc3d09b2":{
      "scriptId":"u7"},
    "b6dfc909bdc14431ad4d234ab055ed68":{
      "scriptId":"u8"},
    "dc982a81bac944499cfe6ec69ec2dee2":{
      "scriptId":"u9"},
    "bf3256edd094403195c3094dd8c36ce5":{
      "scriptId":"u10"},
    "42adec42b34945889fa3ffaddecfbf23":{
      "scriptId":"u11"},
    "ec4907af9e04429babb079e298278916":{
      "scriptId":"u12"},
    "d19e245feaa24d7499acfbf10ea38650":{
      "scriptId":"u13"},
    "06ed96fd273c42368d2b89e69dc94f77":{
      "scriptId":"u14"},
    "e4a42adef0dc4314bad2a1f557a7623b":{
      "scriptId":"u15"},
    "17e4645246cd43dd9432d74867275b14":{
      "scriptId":"u16"},
    "9584f1f17a3242c5ad81386d4813ed14":{
      "scriptId":"u17"},
    "aae82c4c9f0c4231abaf0895931c7e37":{
      "scriptId":"u18"},
    "2861c88ced0c40f196eef7ec87ef76ad":{
      "scriptId":"u19"},
    "af499a8e1e7745609f0cf7bffa00eb66":{
      "scriptId":"u20"},
    "6d9dd85f54664f6bb01808bcf6f8cb1e":{
      "scriptId":"u21"},
    "344c763ece0a4224bcfc35a36a14f424":{
      "scriptId":"u22"},
    "a0fbc40adfc443ad904cf1d92a3095d4":{
      "scriptId":"u23"},
    "0061b0fbe4b24039886b569023b14e89":{
      "scriptId":"u24"},
    "f038a670bc534526a2d1277ae31af188":{
      "scriptId":"u25"},
    "85b5f5a26cfe4cc899c3ffa8df785070":{
      "scriptId":"u26"},
    "4b137f8a25e749ed8bacdfebf1fa8507":{
      "scriptId":"u27"},
    "bdb8d5aff2464eb3931f8c95ec82ba7c":{
      "scriptId":"u28"},
    "9f823a7286a847e1ac586db1cf2ba9b7":{
      "scriptId":"u29"},
    "9ee9e81928e24a4197787fafabfca78e":{
      "scriptId":"u30"},
    "56df43801f014a8c9d742616da99916b":{
      "scriptId":"u31"},
    "42f70840504b4587beb4f2b70444ecc6":{
      "scriptId":"u32"},
    "83faa0e8e6e042e2bd090f0510a97d93":{
      "scriptId":"u33"},
    "f3beadc99a1947a0bd056241a2c070e5":{
      "scriptId":"u34"},
    "c5d6a857eb4c45ff8a563fb357952f37":{
      "scriptId":"u35"},
    "fd05f527bff94d8db756f463cbe6b812":{
      "scriptId":"u36"},
    "b3743e2a21074ec5916a7be903f3ffdd":{
      "scriptId":"u37"},
    "8f918dbfe46c40eb99a33d32ce9fa9af":{
      "scriptId":"u38"},
    "ff07ca78d75b49b582f1af1ebd6d47a2":{
      "scriptId":"u39"},
    "4bf2b7e04812431ba12468300b114725":{
      "scriptId":"u40"},
    "867bc32adfa7431d8d7e6e1ff5e0beef":{
      "scriptId":"u41"},
    "03c85fc399c648e9946d50960ad49cfd":{
      "scriptId":"u42"},
    "41f5332d7d7e40aea1169a71e413e315":{
      "scriptId":"u43"},
    "247999c2cfd043a9a81a15821385ba5b":{
      "scriptId":"u44"},
    "7ff8bd5bbc2946c0b0bc926d7a1c1e40":{
      "scriptId":"u45"},
    "1aadfffa46874d4291091f2406706e26":{
      "scriptId":"u46"},
    "0184fb4a02ab46a7a448e529b838e803":{
      "scriptId":"u47"},
    "509dc05f893647c9b510846f3531a7fd":{
      "scriptId":"u48"},
    "354575cf587c4e4382f3608fe0c582ed":{
      "scriptId":"u49"},
    "3083a0880e8e4ff2a306f8a8e61ad379":{
      "scriptId":"u50"},
    "e9ae733247c84c629ec32d411da72f49":{
      "scriptId":"u51"},
    "11fc0f5fe2b749169270c83488be243f":{
      "scriptId":"u52"},
    "8d4e58f2b7204e14adde2f9f9d004fb9":{
      "scriptId":"u53"},
    "687a121037474323bb48bc8cf726364b":{
      "scriptId":"u54"},
    "ce2bac0a939843a79795e2565e969744":{
      "scriptId":"u55"},
    "aa5011c92b3a41a9a13445cfda0f5804":{
      "scriptId":"u56"},
    "ee5de38c0fac4ff2b99a79772c44453c":{
      "scriptId":"u57"},
    "5ec25adda8e24c47af47196607bdd8aa":{
      "scriptId":"u58"},
    "fadd9412665b4562a4ca2e5e3f52147e":{
      "scriptId":"u59"},
    "b6980d0021ce4fc687723a4a93b98bdb":{
      "scriptId":"u60"},
    "ab2274655d9d47db82f035348798e766":{
      "scriptId":"u61"},
    "9eac0487c2f446b88ba927ee36e9cd88":{
      "scriptId":"u62"},
    "ed90a1242d1b45648ae496bf05503cc2":{
      "scriptId":"u63"},
    "2b64c6f79b4e45758bc9caf4df255b2c":{
      "scriptId":"u64"},
    "c0d49ac680cd474ebf3304d0c7da5aaa":{
      "scriptId":"u65"},
    "3cd1decd3b7f4dbda141704e8810d7f7":{
      "scriptId":"u66"},
    "c9a55350cb5140bd9d39cf8d2888d092":{
      "scriptId":"u67"},
    "8bd156236da744e19a637efaef624066":{
      "scriptId":"u68"},
    "5b9e20ab20da4680b064a69d9a22351d":{
      "scriptId":"u69"}}});