$axure.loadCurrentPage({
  "url":"profile.html",
  "generationDate":new Date(1413920306012.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"X",
"Y",
"GPSx",
"GPSy",
"Prox",
"Proy",
"Musicx",
"Musicy",
"Newappx",
"Newappy",
"Settingsx",
"Settingsy",
"swapx",
"swapy",
"Customize"],
  "page":{
    "packageId":"9c8468c15c7a4e4291037a4475fa81cf",
    "type":"Axure:Page",
    "name":"Profile",
    "notes":{
      "Instructions":"<p><span>Personal Settings Page, Location submenu</span></p><p><span>&nbsp;&nbsp; - Preset Categories like Restaurants and Shops are provided.</span></p><p><span>&nbsp;&nbsp; - User can create new categories using the &quot;New category&quot; button</span></p><p><span>&nbsp;&nbsp; - User can add a preferable location using the &quot;Add Location&quot; button</span></p><p><span>&nbsp;&nbsp; - These locations are registered online on volvo server as personal information </span></p><p><span>&nbsp;&nbsp; - By clicking the back icon you return to the profile home screen</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e05fdf91990f4c0aad61e2eae1115686",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b34d3170f7d4a9d8a9eb3fd9101c93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/profile/u0.png"}},
{
          "id":"f75a972b05a5474ca9344b81bf568de9",
          "label":"Back",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":40,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Main in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"96be03e6f58941e7bdd2bccfc76623b5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "e05fdf91990f4c0aad61e2eae1115686":{
      "scriptId":"u0"},
    "8b34d3170f7d4a9d8a9eb3fd9101c93c":{
      "scriptId":"u1"},
    "f75a972b05a5474ca9344b81bf568de9":{
      "scriptId":"u2"}}});